version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - type: volume
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  diProxy:
    image: arczipt/di-proxy
    restart: on-failure
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_URL: mongodb://root:example@mongo:27017/
      RUNS_PATH: /di/runs
      ANALYSES_PATH: /di/alice/ANALYSES
      WORK_DIR: /di/alice/sw/
      ALIBUILD_ARCH_PREFIX: ubuntu2004_x86-64/
      DI_DATASETS: /di/datasets
    volumes:
      - type: bind
        source: /home/arczipt/alice
        target: /di/alice
      - type: bind
        source: /home/arczipt/DATASETS
        target: /di/datasets
        read_only: true
      - type: volume
        target: /di/runs
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    depends_on:
      - mongo