version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  diProxy:
    image: arczipt/di-proxy
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo