version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  diProxy:
    image: arczipt/di-proxy
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_URL: mongodb://root:example@mongo:27017/
      RUNS_PATH: /di/runs
      ANALYSES_PATH: /di/analyses
      WORK_DIR: /di/alice/sw/
      ALIBUILD_ARCH_PREFIX: ubuntu2004_x86-64/
      O2_VERSION: O2/latest-DataInspector-o2/
    volumes:
      - type: bind
        source: /home/arczipt/alice
        target: /di/alice
        read_only: true
      - type: volume
        target: /di/runs
      - type: volume
        target: /di/analyses
    depends_on:
      - mongo