version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - type: volume
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  diProxy:
    image: arczipt/di-proxy
    restart: on-failure
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/
      RUNS_PATH: /di/runs
      DI_DATASETS: /di/datasets
      WORK_DIR: /di/alice-sw
      ALIBUILD_ARCH_PREFIX: ubuntu2004_x86-64/
    volumes:
      - type: bind
        source: ${ALIBUILD_WORK_DIR}
        target: /di/alice-sw
        read_only: true
      - type: bind
        source: /home/arczipt/DATASETS
        target: /di/datasets
        read_only: true
      - type: volume
        target: /di/runs
    depends_on:
      - mongo