#!/bin/bash

GITHUB_URL="$1"
BRANCH="$2"
ANALYSIS_ID="$3"

cd "$O2PHYSICS_PATH" || exit

REMOTE_NAME="source-$ANALYSIS_ID"
BRANCH_NAME="build-$ANALYSIS_ID"

git remote add "$REMOTE_NAME" "$GITHUB_URL"
git fetch "$REMOTE_NAME"
git checkout -b "$BRANCH_NAME" "$REMOTE_NAME/$BRANCH"

cd ../
aliBuild build O2Physics --defaults o2
