#!/bin/bash

DI_O2_BUILD_PATH="$WORK_DIR/$ALIBUILD_ARCH_PREFIX/$O2_VERSION"

GITHUB_URL="$1"
ANALYSIS_ID="$2"

cd "$ANALYSES_PATH" || exit
mkdir "$ANALYSIS_ID"
cd "$ANALYSIS_ID" || exit

git clone "$GITHUB_URL" CODE
mkdir BUILD
cd BUILD || exit

source "$DI_O2_BUILD_PATH/etc/profile.d/init.sh"

cmake ../CODE -DlibjalienO2_ROOT="$LIBJALIENO2_ROOT"
cmake --build .
