#!/bin/bash

GITHUB_URL="$1"
BRANCH="$2"
ANALYSIS_ID="$3"

cd "$ANALYSES_PATH" || exit
mkdir "$ANALYSIS_ID"
cd "$ANALYSIS_ID" || exit

BRANCH_NAME="analysis-$ANALYSIS_ID"

aliBuild init O2 --defaults o2 -w "$WORK_DIR" -c "$ALI_DIR/alidist"
cd O2 || exit
git remote add origin "https://github.com/O2DataInspector/AliceO2.git"
git fetch
git checkout data-inspector-cleaned
cd ../

aliBuild init O2Physics --defaults o2 -w "$WORK_DIR" -c "$ALI_DIR/alidist"
cd O2Physics || exit
git remote add origin "$GITHUB_URL"
git fetch
git checkout -b "$BRANCH_NAME" "remotes/origin/$BRANCH"
cd ../
aliBuild build O2Physics --defaults o2 -w "$WORK_DIR" -c "$ALI_DIR/alidist"
