#!/bin/bash

RUN_ID="$1"
BUILD_PATH="$2"
WORKFLOW="$3"
CONFIG="$4"

source "$BUILD_PATH/etc/profile.d/init.sh"

PROG="$BUILD_PATH/bin/$WORKFLOW"
mkdir "$RUNS_PATH/$RUN_ID"
cd "$RUNS_PATH/$RUN_ID" || exit
$PROG --inspector --batch --inspector-id "$RUN_ID" "$CONFIG"
